### ISSUE TITLE
Add user site-packages to ipython path

### ISSUE THREAD

**Issue by andersla** [pharmbio/notebook-playground#4]
Current workaround to get site-packages installed with `pip install --user packagename` into jupyter path:

```
import sys
sys.path.append('/home/jovyan/.local/lib/python3.6/site-packages')
```
Could probably be added to JUPYTER_PATH in helm chart as env

**Comment by Snapple49** [comment]
Fixed with 91d0791e3a57aef032be68b3c5941137e2001f05!
