### ISSUE TITLE
remove tfSupport option?

### ISSUE THREAD

**Issue by andersla** [pharmbio/notebook-playground#8]
Do we need this option now when vm:s have better cpu config?

**Comment by Snapple49** [comment]
No this should be obsolete now! Can be removed in next build :+1:

**Comment by Snapple49** [comment]
This is actually in https://github.com/pharmbio/helm-charts :) Fixed now in https://github.com/pharmbio/helm-charts/commit/7656b14b4c7100e25374786bfd6fec81deabc84d
